### ISSUE TITLE
travis fail on repo name

### ISSUE THREAD

**Issue by markstur** [IBM/watson-banking-chatbot#10]
Skipping a deployment with the script provider because this repo's name does not match one specified in .travis.yml's deploy.on.repo: IBM/conversational-banking

**Comment by sauravraiguru** [comment]
Hi Mark, I have updated the repo-name and attached the buildcheck link of travis in Readme.md.
we do not have admin rights, so maybe you can re-trigger a build for us.

**Comment by markstur** [comment]
travis tests are still not implement (so currently fail) but this specific issue is closed.
