### ISSUE TITLE
Push button deploy fail: An operation for service instance wbc-discovery-service is in progress.

### ISSUE THREAD

**Issue by markstur** [IBM/watson-banking-chatbot#100]
Creating app watson-banking-chatbot-20190408212730597...
Mapping routes...
Binding services...
FAILED
Unexpected Response
Response code: 409
CC code:       60016
CC error code: CF-AsyncServiceInstanceOperationInProgress
Description:   An operation for service instance wbc-discovery-service is in progress.

Finished: FAILED

**Comment by tashanemclean** [comment]
I've had this samae issue. According to your log, in the Description section, It says an operation for service instance of 'wbc-discovery-service' is still in progress. If you wait until the Status in your Resource List says 'Provisioned' then running the deploy again should work.

**Comment by ashkaps** [comment]
@markstur  was this resolved automatically?

**Comment by markstur** [comment]
@ashkaps You need to hit the Run button.  The problem goes away after a brief startup of the service but the app does not restart automatically so hit the button.  FYI it is noted under troubleshooting in the README.

**Comment by ashkaps** [comment]
@markstur I tried that a couple of times and waited for over a day to let it resolve. I had to delete everything in account and start from scratch. 
Error was some async operation that wouldnt finish. A fresh start fixed it. Not sure what really the problem was. 
Thanks though!

**Comment by markstur** [comment]
^ that is not normal. If we can capture what happened we should open a new issue to document it. I'll guess we cannot reproduce it though. If that's the case, no need to keep another issue open.
