### ISSUE TITLE
RnR

### ISSUE THREAD

**Issue by upwardstudios** [IBM/watson-banking-chatbot#12]
Retrieve and Rank , docs do not upload ,except the docx ones. Any ideas ? I have the conversion service too

**Comment by markstur** [comment]
The docx ones are the only docs to upload.  Also we've now converted the app to use Discovery so no conversion needed and the upload is automatic with the deploy to bluemix button and the README should be complete for manual upload.  Note the text files are still there for training, but we are not doing training with Discovery yet.
