### ISSUE TITLE
Upgrade conversation workspace

### ISSUE THREAD

**Issue by markstur** [IBM/watson-banking-chatbot#13]
Watson says I should "Upgrade to the latest version to enable new features" with the current workspace loaded from JSON. I'm assuming it should be upgraded, tested, exported so that we can get rid of that message and also validate with latest version.

**Comment by sauravraiguru** [comment]
Hi Mark, I have re-added the workspace by downloading it from a new conversation workspace to eliminate any warnings coming in from an old conversation service.
