### ISSUE TITLE
Discovery setup fails when environment is not yet 'available'. Restart should fix.

### ISSUE THREAD

**Issue by markstur** [IBM/watson-banking-chatbot#21]
The automatic setup of Discovery typically tries to create a collection before the environment is ready. This causes an error. On restart (should be automatic on bluemix) the problem goes away.

Ideally the code would do some wait-for-available logic to make this more seamless.

**Comment by Natiqah07** [comment]
hey mark! I am atiqah, i asked for your advice on your youtube channel. i am currently using python and am still trying to input discovery in it. do you mind helping me? currently this is my working file

thank you for your help

[alexa-ask-watson-master (3).zip](https://github.com/IBM/watson-banking-chatbot/files/1452332/alexa-ask-watson-master.3.zip)

**Comment by markstur** [comment]
Hi Atiqah, for python discovery query take a look here https://github.com/IBM/watson-online-store/blob/master/watsononlinestore/watson_online_store.py#L709  -- the query call is easy. To format the response you'll need to look at the contents. It will usually give you much more than a conversation response.
