### ISSUE TITLE
How to integrate this app with the speech to text and Text to speech  services??

### ISSUE THREAD

**Issue by salmaadel** [IBM/watson-banking-chatbot#36]
Here is what I added in app.js file:

```
// ADD SPEECH TO TEXT INTEGRATION CODE HERE

var sttEndpoint = vcap.speech_to_text[0].credentials.url;
var stt_credentials = Object.assign({
username: process.env.SPEECH_TO_TEXT_USERNAME || 'aaa',
password: process.env.SPEECH_TO_TEXT_PASSWORD || 'bbb',
url: process.env.SPEECH_TO_TEXT_URL ||
'https://stream.watsonplatform.net/speech-to-text/api',
version: 'v1',},vcap.speech_to_text[0].credentials);

// ADD TEXT TO SPEECH INTEGRATION CODE HERE

var ttsEndpoint = vcap.text_to_speech[0].credentials.url;
var tts_credentials = Object.assign({
username: process.env.TEXT_TO_SPEECH_USERNAME || 'xxx',
password: process.env.TEXT_TO_SPEECH_PASSWORD || 'yyy',
url: process.env.TEXT_TO_SPEECH_URL ||
'https://stream.watsonplatform.net/text-to-speech/api',
version: 'v1',
},vcap.text_to_speech[0].credentials);
// Endpoint to be call from the client side
app.post('/api/message', function(req, res) {
	var workspace = process.env.WORKSPACE_ID || '<workspace-id>';
	if (!workspace || workspace === '<workspace-id>') {
		return res.json({
			'output': {
				'text': 'The app has not been configured with a <b>WORKSPACE_ID</b> environment variable. Please refer to the ' + '<a href="https://github.com/watson-developer-cloud/conversation-simple">README</a> documentation on how to set this variable. <br>' + 'Once a workspace has been defined the intents may be imported from ' + '<a href="https://github.com/watson-developer-cloud/conversation-simple/blob/master/training/car_workspace.json">here</a> in order to get a working application.'
			}
		});
	}

//ADD TEXT TO SPEECH GET TOKEN ENDPOINT HERE
app.get('/api/text-to-speech/token', function(req, res, next){
watson.authorization(tts_credentials).getToken({ url:
tts_credentials.url }, function(error, token){
if (error) {
if (error.code !== 401)
return next(error);
} else {
res.send(token);
}
});
});

//ADD SPEECH TO TEXT GET TOKEN ENDPOINT HERE

app.get('/api/speech-to-text/token', function(req, res, next){
watson.authorization(stt_credentials).getToken({ url:
stt_credentials.url }, function(error, token){
if (error) {
if (error.code !== 401)
return next(error);
} else {
res.send(token);
}
});
});`
```

**Comment by salmaadel** [comment]
and here is what I added in index.html file

It is not working even the mic and speaker didn't appear on screen

 <body>
  <div id="view-change-button" class="button" onclick="PayloadPanel.togglePanel(event, this)">
    <img class="option full" src="../img/Chat Button.png">
    <img class="option not-full" src="../img/Code Button.png">
  </div>
  <div id="contentParent" class="responsive-columns-wrapper">
    <div id="chat-column-holder" class="responsive-column content-column">
     
     <div id="output-audio" class="audio-on" onclick="TTSModule.toggle()" value="ON"></div>
      <div class="chat-column">
        <div id="scrollingChat"></div>
        <div id="input-wrapper" class="responsive-columns-wrapper">
	       
         <div id="input-mic-holder">
         <div id="input-mic" class="inactive-mic" onclick="STTModule.micON()">
          </div>
          </div>
	        <label for="textInput" class="inputOutline">
	          <input id="textInput" class="input responsive-column"
	            placeholder="Type something" type="text"
	            onkeydown="ConversationPanel.inputKeyDown(event, this)">
	        </label>
	     </div>
      </div>
    </div>
    <div id="payload-column" class="fixed-column content-column">
      <div id="payload-initial-message">
        Type something to see the output
      </div>
      <div id="payload-request" class="payload"></div>
      <div id="payload-response" class="payload"></div>
    </div>
  </div>

**Comment by salmaadel** [comment]
Here is what I added in index.html file

It didn't work and mic nor speaker appeared on screen

`<body>
  <div id="view-change-button" class="button" onclick="PayloadPanel.togglePanel(event, this)">
    <img class="option full" src="../img/Chat Button.png">
    <img class="option not-full" src="../img/Code Button.png">
  </div>
  <div id="contentParent" class="responsive-columns-wrapper">
    <div id="chat-column-holder" class="responsive-column content-column">
     
     <div id="output-audio" class="audio-on" onclick="TTSModule.toggle()" value="ON"></div>
      <div class="chat-column">
        <div id="scrollingChat"></div>
        <div id="input-wrapper" class="responsive-columns-wrapper">
	       
         <div id="input-mic-holder">
         <div id="input-mic" class="inactive-mic" onclick="STTModule.micON()">
          </div>
          </div>
	        <label for="textInput" class="inputOutline">
	          <input id="textInput" class="input responsive-column"
	            placeholder="Type something" type="text"
	            onkeydown="ConversationPanel.inputKeyDown(event, this)">
	        </label>
	     </div>
      </div>
    </div>
    <div id="payload-column" class="fixed-column content-column">
      <div id="payload-initial-message">
        Type something to see the output
      </div>
      <div id="payload-request" class="payload"></div>
      <div id="payload-response" class="payload"></div>
    </div>
  </div>
`

**Comment by salmaadel** [comment]
@markstur kindly review

**Comment by markstur** [comment]
Probably better to get speech-to-text and mic working with this example first before trying to add it here. Have you tried this example?
https://github.com/watson-developer-cloud/speech-javascript-sdk/tree/master/examples?cm_mc_uid=43063140565014992688038&cm_mc_sid_50200000=1501512863
