### ISSUE TITLE
auto-configure bluemix services

### ISSUE THREAD

**Issue by stevemart** [IBM/watson-banking-chatbot#4]
we should use https://github.com/watson-developer-cloud/node-sdk and the VCAP credentials to auto-configure the conversation and r&r service with the artifacts in data/

**Comment by sauravraiguru** [comment]
- configured deploy2bluemix using VCAP credentials. It is being deployed in IBM Jazz DevOps and the new Toolchain as well.

**Comment by markstur** [comment]
done
