### ISSUE TITLE
Deploy fails due to long host name

### ISSUE THREAD

**Issue by RiyaMRoy04** [IBM/watson-banking-chatbot#42]
Deploy is failing due to long hostname. Can random route be set to false for successful deployment at first attempt?

**Comment by stevemart** [comment]
We've done that before in some apps, like https://github.com/IBM/watson-discovery-news/blob/master/manifest.yml#L13 so yah, go ahead and submit a PR if you'd like

**Comment by sauravraiguru** [comment]
If we make it false, the 1st deployment will work, but post that all deployments you need to put in your own app-name to make it unique.
- I suppose we should keep it as it is, it fails only sometimes when there is an exact conflict in datetime() while deploying, else the developer can always change the route name before 'deploy' in toolchain.

**Comment by RiyaMRoy04** [comment]
@sauravraiguru  Thanks for the suggestion. But have been facing this issue due to "long hostname with random words" while random route is enabled(as shown in screenshot below). There is a character limit for hostname due to which deployment fails at first attempt most of the times! When random route is set to false it just picks up timestamp and host name will be much shorter and still unique! 
![picture1](https://user-images.githubusercontent.com/11567379/31281240-7ab0cb08-aacc-11e7-9177-b8c304bc0f17.png)

And you can't change "route name" before 'deploy' in toolchain when the random route is enabled.You can only change APP NAME. It still picks up the random route(shown in the screenshot below). Telling a developer to change the "APP NAME" is a workaround but again a manual process! Hence, had suggested it!
![screen shot 2017-10-06 at 7 09 58 pm](https://user-images.githubusercontent.com/11567379/31280801-2e58deae-aacb-11e7-86db-e5e0827b29cf.png)

Thanks @stevemart I think we should set it to false since sometimes it is just failing to deploy in the first attempt itself.

**Comment by markstur** [comment]
yes, please set it to false. The timestamp should be unique enough. The random route was only needed when the host name was specified in the manifest. It looks like that part was already fixed.

**Comment by sauravraiguru** [comment]
@RiyaMRoy04 Thanks for the information! I did try it a few times & it did not fail, but anyway timestamp way to keep the APP_NAME unique. As suggested you can send in a PR.

P.S If this is a known issue that APP_NAME is having a char_limit & this is exceeded by random-route, we should let the CF team know about this.

**Comment by RiyaMRoy04** [comment]
@sauravraiguru I was talking about HOST NAME or ROUTE NAME and not APP NAME. Thanks, shall send PR.. It failed in many instances when we had done workshop and had to re-deploy multiple times. Hence!
