### ISSUE TITLE
improve test coverage

### ISSUE THREAD

**Issue by stevemart** [IBM/watson-banking-chatbot#5]
test coverage is pretty minimal right now

**Comment by sauravraiguru** [comment]
- Our journey being in NodeJS with html, css we have minimal testing now because we have only one orchestrator file that largely works with Conversation & RnR.
- More data/industry oriented journey where most details lie in WCS & RnR.

**Comment by stevemart** [comment]
Closed by https://github.com/IBM/watson-banking-chatbot/pull/17
