### ISSUE TITLE
Repository URL is not valid. The repository must be on https://git.ng.bluemix.net

### ISSUE THREAD

**Issue by RiyaMRoy04** [IBM/watson-banking-chatbot#52]
@markstur Facing this issue! Please help!

Repository URL is not valid. The repository must be on https://git.ng.bluemix.net

![screen shot 2017-11-29 at 3 02 50 pm](https://user-images.githubusercontent.com/11567379/33368053-6e4f940c-d4e8-11e7-889f-22f903f432df.png)

**Comment by sauravraiguru** [comment]
@RiyaMRoy04 Please select Repository Type as 'Clone' as this is not an existing repository in git.ng.bluemix.net domain.
- It will clone the repository from external github repo URL and proceed towards creating the delivery pipeline.

**Comment by RiyaMRoy04** [comment]
@sauravraiguru  Thanks Saurav! 🥇 We should definitely add this to troubleshooting for the benefit of newbies!

**Comment by RiyaMRoy04** [comment]
@sauravraiguru  Hitting with this error while deploying the application to IBM Cloud after selecting Repository Type as "Clone"

![screen shot 2017-12-21 at 1 07 45 pm](https://user-images.githubusercontent.com/11567379/34245581-6694ead2-e622-11e7-9579-858c1fd1516f.png)

Looks like it is looking for that service rather than creating a new service.Some config has to be changed. However, this works fine locally! 👍

**Comment by sauravraiguru** [comment]
After the migration to IBM cloud, its not creating the new services as required.(we need to create)

-The other issue is are you able to deploy in UK region? which is where most of the users would try out and there is no devops available there

**Comment by dolph** [comment]
@sauravraiguru Just as an aside, do you have any idea why the repository "type" is even a choice? It seems the answer should be easily detected based on the given URL. "Existing" is sufficiently vague that I completely understand @RiyaMRoy04's confusion here (I certainly thought this was a valid issue as presented in the description).

**Comment by dolph** [comment]
I'm closing this, assuming it's not a problem anymore. Please re-open if that's not true!
