### ISSUE TITLE
Starter Kit:  Create ChatBot project fails

### ISSUE THREAD

**Issue by lemacomb** [IBM/watson-banking-chatbot#58]
Attempted to create a Wealth Management Chatbot project from the FinTech Starter kit.  The creation of the project failed with no error information.  See attached screen capture.

![chatbotprojectfailed](https://user-images.githubusercontent.com/30877682/36288100-10dd1236-1287-11e8-9703-f14f7b573df1.JPG)

**Comment by stevemart** [comment]
@lemacomb can you re-post the issue here: https://github.com/IBM/personal-wealth-portfolio-mgt-bot ? This appears to be an issue with a different repo.
