### ISSUE TITLE
Question - How are watson-conversation-setup.js and watson-discovery-setup.js used to setup Watson services in IBM cloud?

### ISSUE THREAD

**Issue by lee-zhg** [IBM/watson-banking-chatbot#69]
Hi, I try to figure out How watson-conversation-setup.js and watson-discovery-setup.js are used to setup Watson services in IBM cloud? Where are they called? Is there any additional required configuration?

I like to reuse the same logic.

Thanks
Lee

**Comment by stevemart** [comment]
Hi @lee-zhg we use `watson-conversation-setup.js` when the app is initialized for the first time. See https://github.com/IBM/watson-banking-chatbot/blob/a305473958208c8342289eb2f067395060435c7d/app.js#L116-L126 

The intention, for `watson-conversation-setup.js`, is to upload the conversation dialog (https://github.com/IBM/watson-banking-chatbot/blob/master/data/conversation/workspaces/banking.json) using the Node SDK. 

We mainly do this so the user doesn't have to: 1) clone the repo, 2) go through IBM Cloud find their service, 3) launch Watson Assistant tooling, 4) upload the workspace, 5) reload the app.

It's particularly useful when showing demos of this chatbot.

**Comment by stevemart** [comment]
Oh, and `watson-discovery-setup` accomplishes the same thing (except we push documents to discovery instead of a conversation dialog), and is used around the same time.
