### ISSUE TITLE
manifest asks for standard services instead of free. 

### ISSUE THREAD

**Issue by markstur** [IBM/watson-banking-chatbot#8]

**Comment by markstur** [comment]
Corrected. It does run, but gives warnings. Would want dev journey to use free where possible.

**Comment by sauravraiguru** [comment]
Yes Mark, we had started off using free plans of APIs, but as an example we are having more than 25 intents in the conversation workspace. So, used the standard plan

**Comment by markstur** [comment]
Mostly done.  Tone Analyzer needs to change to "Lite" (which is a free plan).  The others are now on free.

**Comment by markstur** [comment]
Resolved in #46
