### ISSUE TITLE
Can I use the code In Android app ?

### ISSUE THREAD

**Issue by MostafaKhaled2017** [IBM/watson-banking-chatbot#86]
I was wondering if I can use it in Android application

**Comment by stevemart** [comment]
@MostafaKhaled2017 feel free to use the code for whatever you like! :) Fork it, modify it, do whatever you like. It's all Apache licensed.

**Comment by MostafaKhaled2017** [comment]
How can I use it in the Android app ??

**Comment by sauravraiguru** [comment]
@MostafaKhaled2017 This code is written in NodeJS, hence will not work in Android. But you can fork & use the code snippets/logic to convert to an android version :)
