### ISSUE TITLE
How can I use the chatbot in Android app

### ISSUE THREAD

**Issue by MostafaKhaled2017** [IBM/watson-banking-chatbot#87]
I want to use this chatbot in Android app how can I do that ?

**Comment by markstur** [comment]
You can run this in your browser on Android.  If you need a native android app there are other resources for creating one.  Maybe start here to see android with watson:
https://developer.ibm.com/tutorials/use-watson-android-sdk-in-android-studio/

**Comment by MostafaKhaled2017** [comment]
This tutorial is old now there is no user name and password for the TTS and STT services
