### ISSUE TITLE
Errors in deploying the faq bot locally

### ISSUE THREAD

**Issue by shahamit** [IBM/watson-banking-chatbot#97]
I am trying to deploy the FAQ bot but I am facing a few challenges. I have a few questions too

1. Importing a skill with the banking.json file is failing after multiple retries with an error "We could not import your Skill. Unable to fetch access token for account: 382fd61942c14fa287c5f95e3c1b5274"
2. Can this FAQ bot be tweaked for a different domain by changing the documents uploaded for the discovery service (and not having any intents, entities and dialogs)?

Thanks!

**Comment by markstur** [comment]
re: 2) Yes, the idea is you can take the code and "tweak" it. It might be more than a tweak, but adding new documents and using this as a starting put should work for you

re: 1) I just created an assistant service and imported the banking.json successfully. I'm assuming you tried importing it in the IBM Cloud/Assistant Tool UI.  It looks like something specific to your account. I think you should [Contact IBM Cloud Support](https://cloud.ibm.com/unifiedsupport/supportcenter).

**Comment by shahamit** [comment]
Thanks for the quick help. I was able to import the banking.json by starting the browser in incognito mode. 
It would appreciate if you could share your thoughts on the below questions about the app -
1. Can I configure the app to not have a watson assistant and make the chatbot directly query only the watson discovery service? if so how can I do so?
2. Does the chatbot generate answer or does it paste the results of the search in the discovery service?
For e.g. with the current banking chat bot referring to the BankRnR-OMP-General.docx, if I ask the question "I didn't not receive my cashback. What do I do?", it returns the result as "We regret the inconvenience. Please try again. Please call the merchant Customer care for any queries regarding the product or payment confirmation" while the document has the question and answer in a different format. Is it generating the answer or there is some other document that has details about cashback failures?

Thanks.

**Comment by markstur** [comment]
1. The discovery lookup code is here:
https://github.com/IBM/watson-banking-chatbot/blob/master/app.js#L574
after "else if (data.context.action.lookup === DISCOVERY_ACTION) {".
You can take that code and run it instead of assistant message. It is pretty simple input from user, sent to query, return response. The conversation won't be as nice, but if you just want query/response you can do that.

2. The chatbot tries to answer the easy questions and only uses discovery when it needs to. This is the short-tail, long-tail strategy. Unfortunately there is too much overlap. So you are probably seeing assistant try to answer things that were also in the FAQ docs.

**Comment by shahamit** [comment]
I tried configuring the chatbot to use a discovery service that had different/custom documents uploaded instead of the banking documents (I removed the [default config](https://github.com/IBM/watson-banking-chatbot/blob/b5fe48ae89bcb2826243460429860786c0bf9b00/app.js#L44) to load them too). 
It seems the query isn't going to the discovery service. I see the below log in the command prompt

assistant.message ::  {"intents":[],"entities":[],"input":{"text":"password policy"},"output":{"text":["I didn't understand. You can try rephrasing."],"nodes_visited":["Anything else"],"log_messages":[]}

1. Do I need any configuration to let the chatbot know that it should fallback on the discovery service if the assistant isn't able to respond to user question?

2. How can enable more logging on the command prompt? I see a lot of console.log() statements in the javascript source files but how can I enable to view them?

Thanks.

**Comment by markstur** [comment]
The current code only does the discovery lookup when the conversation tells it to.
```
} else if (data.context.action.lookup === DISCOVERY_ACTION) {
```
If you want it to always do the lookup, you can change the condition. Your current example hit the "Anything Else" node. So you could also key off of that.
