### ISSUE TITLE
Workspace exceeds lite plan limit of 100 dialog nodes

### ISSUE THREAD

**Issue by floresam** [IBM/watson-banking-chatbot#99]
This pattern can not be executed with a lite plan Watson Assistant instance due to the lite plan limit of 100 dialog nodes. Is it possible to reduce the number of dialog nodes in banking.json to enable folks with lite accounts to benefit from this code pattern?

**Comment by adityatadadikar** [comment]
Im also facing the same above issue.
![Capture](https://user-images.githubusercontent.com/47084145/54151055-f4229600-445f-11e9-90b4-15d7eb26060b.PNG)

**Comment by tiagosteil** [comment]
I also have this problem. Has anyone found any solutions?

**Comment by markstur** [comment]
Fixed in  #101 

Default dialog now has ~93 nodes. Should work for you.
